In [1]:
import pandas as pd
import numpy as np

In [13]:
order_items = pd.read_csv(r"C:\Users\Anuj Kumar\OneDrive\Desktop\Data cleaning\olist_order_items_dataset.csv")
customers = pd.read_csv(r"C:\Users\Anuj Kumar\OneDrive\Desktop\Data cleaning\olist_customers_dataset.csv")
products = pd.read_csv(r"C:\Users\Anuj Kumar\OneDrive\Desktop\Data cleaning\olist_products_dataset.csv")
orders = pd.read_csv(r"C:\Users\Anuj Kumar\OneDrive\Desktop\Data cleaning\olist_orders_dataset.csv")

In [44]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        99441 non-null  object
 1   customer_zip_code  99441 non-null  int64
 2   customer_city      99441 non-null  object
 3   customer_state     99441 non-null  object
dtypes: int64(1), object(3)
memory usage: 3.0+ MB

In [15]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [23]:
print(customers["customer_city"].nunique())
print(customers["customer_id"].nunique())
print(customers["customer_state"].nunique())
print(customers["customer_unique_id"].nunique())
print(customers["customer_zip_code_prefix"].nunique())

4119
99441
27
96096
14994

In [24]:
customers.drop("customer_unique_id",axis=1,inplace = True)

In [29]:
state_map = {
    "SP": "Sao Paulo",
    "SC": "Santa Catarina",
    "MG": "Minas Gerais",
    "PR": "Parana",
    "RJ": "Rio de Janeiro",
    "RS": "Rio Grande do Sul",
    "PA": "Para",
    "GO": "Goias",
    "ES": "Espirito Santo",
    "BA": "Bahia",
    "MA": "Maranhao",
    "MS": "Mato Grosso do Sul",
    "CE": "Ceara",
    "DF": "Distrito Federal",
    "RN": "Rio Grande do Norte",
    "PE": "Pernambuco",
    "MT": "Mato Grosso",
    "AM": "Amazonas",
    "AP": "Amapa",
    "AL": "Alagoas",
    "RO": "Rondonia",
    "PB": "Paraiba",
    "TO": "Tocantins",
    "PI": "Piaui",
    "AC": "Acre",
    "SE": "Sergipe",
    "RR": "Roraima"
}

customers["customer_state"] = customers["customer_state"].map(state_map)

In [32]:
customers.rename(columns={"customer_zip_code_prefix":"customer_zip_code"},inplace=True)

In [33]:
customers.head()

,customer_id,customer_zip_code,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,14409,franca,Sao Paulo
1,18955e83d337fd6b2def6b18a428ac77,9790,sao bernardo do campo,Sao Paulo
2,4e7b3e00288586ebd08712fdd0374a03,1151,sao paulo,Sao Paulo
3,b2b6027bc5c5109e529d4dc6358b12c3,8775,mogi das cruzes,Sao Paulo
4,4f2d8ab171c80ec8364f7c12e35b23ad,13056,campinas,Sao Paulo

In [46]:
#Order dataset
orders.info()
orders.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

(99441, 8)

In [59]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivered
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,True
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,True
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,True
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,True
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,True

In [49]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])

In [53]:
cols = ['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']
for c in cols:
    orders[c]=pd.to_datetime(orders[c])

In [60]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivered                      99441 non-null  bool
dtypes: bool(1), datetime64[ns](5), object(3)
memory usage: 6.2+ MB

In [61]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivered                           0
dtype: int64

In [58]:
orders["delivered"] = orders["order_delivered_customer_date"].notnull()

In [89]:
# Merging Customers and orders
df = orders.merge(customers,on='customer_id',how='left')

In [90]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivered,customer_zip_code,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,True,3149,sao paulo,Sao Paulo
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,True,47813,barreiras,Bahia
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,True,75265,vianopolis,Goias
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,True,59296,sao goncalo do amarante,Rio Grande do Norte
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,True,9195,santo andre,Sao Paulo

In [91]:
df.shape

(99441, 12)

In [92]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivered                           0
customer_zip_code                   0
customer_city                       0
customer_state                      0
dtype: int64

In [94]:
# Merge Check
df['order_id'].isnull().sum()

np.int64(0)

In [95]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   product_id           112650 non-null  object
 2   seller_id            112650 non-null  object
 3   shipping_limit_date  112650 non-null  datetime64[ns]
 4   price                112650 non-null  float64
 5   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 5.2+ MB

In [ ]:
order_items.isnull().sum()

In [87]:
order_items.head()

,order_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [83]:
order_items.shape

(112650, 7)

In [84]:
order_items.drop("order_item_id",axis=1,inplace=True)

In [86]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])

In [102]:
df = df.merge(order_items,on="order_id",how="left")

In [103]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivered,customer_zip_code,customer_city,customer_state,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,True,3149,sao paulo,Sao Paulo,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,True,47813,barreiras,Bahia,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,True,75265,vianopolis,Goias,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,True,59296,sao goncalo do amarante,Rio Grande do Norte,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,True,9195,santo andre,Sao Paulo,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 17 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  object
 1   customer_id                    113425 non-null  object
 2   order_status                   113425 non-null  object
 3   order_purchase_timestamp       113425 non-null  datetime64[ns]
 4   order_approved_at              113264 non-null  datetime64[ns]
 5   order_delivered_carrier_date   111457 non-null  datetime64[ns]
 6   order_delivered_customer_date  110196 non-null  datetime64[ns]
 7   order_estimated_delivery_date  113425 non-null  datetime64[ns]
 8   delivered                      113425 non-null  bool
 9   customer_zip_code              113425 non-null  int64
 10  customer_city                  113425 non-null  object
 11  customer_state                 113425 non-null  object
 12  product_id                     112650 non-null  object
 13  seller_id                      112650 non-null  object
 14  shipping_limit_date            112650 non-null  datetime64[ns]
 15  price                          112650 non-null  float64
 16  freight_value                  112650 non-null  float64
dtypes: bool(1), datetime64[ns](6), float64(2), int64(1), object(7)
memory usage: 14.0+ MB

In [105]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 161
order_delivered_carrier_date     1968
order_delivered_customer_date    3229
order_estimated_delivery_date       0
delivered                           0
customer_zip_code                   0
customer_city                       0
customer_state                      0
product_id                        775
seller_id                         775
shipping_limit_date               775
price                             775
freight_value                     775
dtype: int64

In [106]:
df[df["product_id"].isnull()].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivered,customer_zip_code,customer_city,customer_state,product_id,seller_id,shipping_limit_date,price,freight_value
306,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaT,NaT,2017-12-05,False,89288,sao bento do sul,Santa Catarina,NaN,NaN,NaT,NaN,NaN
671,c272bcd21c287498b4883c7512019702,9582c5bbecc65eb568e2c1d839b5cba1,unavailable,2018-01-31 11:31:37,2018-01-31 14:23:50,NaT,NaT,2018-02-16,False,11701,praia grande,Sao Paulo,NaN,NaN,NaT,NaN,NaN
791,37553832a3a89c9b2db59701c357ca67,7607cd563696c27ede287e515812d528,unavailable,2017-08-14 17:38:02,2017-08-17 00:15:18,NaT,NaT,2017-09-05,False,2318,sao paulo,Sao Paulo,NaN,NaN,NaT,NaN,NaN
850,d57e15fb07fd180f06ab3926b39edcd2,470b93b3f1cde85550fc74cd3a476c78,unavailable,2018-01-08 19:39:03,2018-01-09 07:26:08,NaT,NaT,2018-02-06,False,48607,paulo afonso,Bahia,NaN,NaN,NaT,NaN,NaN
1294,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12,False,1151,sao paulo,Sao Paulo,NaN,NaN,NaT,NaN,NaN

In [107]:
df[df["product_id"].isnull()]["order_status"].value_counts

<bound method IndexOpsMixin.value_counts of 306       unavailable
671       unavailable
791       unavailable
850       unavailable
1294         canceled
             ...
113204    unavailable
113236       canceled
113324       canceled
113325    unavailable
113397    unavailable
Name: order_status, Length: 775, dtype: object>